version: '3.9'

services:
  nginx:
    image: nginx:1.24-alpine-slim
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./public/:/var/www/html/public/
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      target: dev
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/

  postgres:
    image: postgres:$POSTGRES_VERSION-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
