branch-defaults:
  main:
    environment: production
    group_suffix: null
global:
  application_name: industrialization-example
  branch: main
  default_ec2_keyname: null
  default_platform: PHP 8.2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application

option_settings:
  aws:elasticbeanstalk:container:php:phpini:
    document_root: /public
